### PR TITLE
Update development environment

### PR DESCRIPTION
**Pull request by mwpastore**
* Add Gemfile to enable easy installation of dev deps from gemspec
* Add missing sqlite3 dev dep
* Pin Sinatra dev dep to avoid Sinatra 2 and Rack 2 compatibility
  issues (for now)
* Pin Rails dev dep to avoid Rails 5 compatibility issues (for now)

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch!  I'm OK with most of this, except the pinning of Sinatra 1.4.x/Rails 4.2.x, unless you have specifically tested Sinatra <1.4,>=2.0 and Rails <4.2,>=5.0 and found them broken.  To be more specific, unless the tests are broken when using all of the following versions:

* Sinatra 1.3.6
* Sinatra 2.0.0.beta1
* Rails 4.1.16
* Rails 5.0.0

then such a change is not acceptable.  I'm fairly sure Forme works with both older versions of Sinatra and Rails.  I'm not sure that it works on newer versions, but if you are getting errors with them, I'd probably want to try to fix them, not ignore them by forcing a specific version range.

FWIW, the tests appear to pass with a deprecation warning on Rails 5.0.0: https://travis-ci.org/jeremyevans/forme/jobs/151001987

In general, I'm very much against '<' or '~' in library gem specs unless you know that newer versions of the dependencies are not compatible.  I'm OK with adding '>=' to the gem specs, you just need to show that that version works and that the version before that does not.

**Comment by mwpastore** [comment]
I was definitely having some conflicts but let me see if I can't narrow it down and reopen up the bottom of the version ranges.

**Comment by jeremyevans** [comment]
Actually, looking at the Sinatra gemspecs, Sinatra >1.0,<2.0 all depend on rack <2, so they would not be compatible with Rails 5, which depends on rack >=2.  I'm guessing this is why Sinatra 1.0 is installed, and sure enough, that's what Travis installs. It looks like Travis skips sinatra testing when testing Rails 5 (on ruby 2.2 and 2.3). One thing to notice about the Travis gemfile is it shows that Forme works on rails 3.2 (ruby 1.8), and rails 4.2 (ruby 1.9-2.1), and I think rails 5.0 (ruby 2.2-2.3).  Maybe I should set the Travis gemfile to test Sinatra 2.0 prerelease on ruby 2.2 so we can see how it goes there.

**Comment by jeremyevans** [comment]
Also, looking at the Travis gemfile reminds me why sqlite3 is not a dev dependency.  On JRuby, you need to use jdbc-sqlite3.  So we would need to remove sqlite3 from the gemspec.

**Comment by mwpastore** [comment]
I'm working on a solution now. :)

**Comment by jeremyevans** [comment]
Looks like things work fine on Sinatra 2.0 beta: https://travis-ci.org/jeremyevans/forme/builds/156315659

One possible option is just renaming .travis.gemfile to Gemfile, tweak .travis.yml, skip the gemspec changes, and include Gemfile.lock in gitignore.  I guess I'm OK with that.  What are your thoughts?

**Comment by mwpastore** [comment]
I was actually thinking we'd wire up .travis.yml and .gemfile to test Forme under different combinations of Rails and Sinatra, e.g.:

### .travis.yml:

```yaml
env:
  - RAILS_VERSION=3.2.22.4 SINATRA_VERSION=1.3.6
  - RAILS_VERSION=4.2.7.1  SINATRA_VERSION=1.4.7
  - RAILS_VERSION=5.0.0.1  SINATRA_VERSION=2.0.0.beta2
```

### .travis.gemfile

```ruby
gem 'rails', ENV['RAILS_VERSION']
gem 'sinatra', ENV['SINATRA_VERSION']
```

Then we'd allow_failures on the Ruby versions we know are incompatible with certain Rails versions. Since you've expressed an interest in checking Forme against different Rails and Sinatra versions, this makes more sense to me, and I think it would strongly validate the compatibility assertions in the README. What do you think?

**Comment by jeremyevans** [comment]
@mwpastore That would seem to increase the number of tests run from 12 to 36, which I think is too hard on Travis.  Currently, we test all of those dependency versions except Sinatra 1.3.6, with the advantage that we automatically test newer tiny versions as they are released. I don't think we really need to test all three Rails and Sinatra versions on all versions of ruby that Forme supports, the benefits aren't really worth the cost IMO.

**Comment by mwpastore** [comment]
Fair enough. I see what you're going for now... using the Ruby version to select the Rails and Sinatra versions and testing kind of the "natural" combinations of things in order. Fingers crossed!

**Comment by jeremyevans** [comment]
Do you think we should keep things as they are, or should we make changes such as renaming .travis.gemfile to Gemfile?

**Comment by mwpastore** [comment]
Sorry, I wasn't clear. I made those changes and just pushed them. They're running through Travis now!

**Comment by jeremyevans** [comment]
Sorry, I should have paid more attention.  The changes look good, as long as Travis is happy with them, I'll merge this.

**Pull request merged**
