### PR TITLE
defined html_safe for padrino view rendering

### PR DESCRIPTION
**Pull request by uptownhr**
added raw html output support for padrino by calling html_safe

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch!  This looks OK, but the file should probably `require 'forme/erb'`.  Also, before this can be merged, the test suite needs to be updated run tests on padrino.

**Comment by jeremyevans** [comment]
Have you had a chance to look into the failing test?  It's failing when you call form in one template with a block, and then you render a partial inside the block, passing the form object as a local variable.  This is probably due to the differences between how Padrino renders (the capture_from_template/capture_html stuff) and how Sinatra (or ERB in general) renders.

If you think this is something you can get working soon, I'll keep this open.  Otherwise, it's probably best to close it.  It can always be reopened later if you do get it working.

**Comment by uptownhr** [comment]
Sorry. Lets close it for now. Id love to work on it but im too
inexperienced...

**Comment by jeremyevans** [comment]
No problem.  If someone is able to work on this, just post here I can reopen.

**Pull request closed without merging**
